### ISSUE TITLE
When click on See All on packages it directs you to optimization client no matter which package documentation you are on

### ISSUE THREAD

**Issue by qci-github** [qci-enablement/qci-data#61]
When you click on see all [https://quantumcomputinginc.com/learn/reference-documentation/emucore-direct](https://quantumcomputinginc.com/learn/reference-documentation/emucore-direct) it redirects to optimization client documentation.

Same thing here [https://quantumcomputinginc.com/learn/reference-documentation/eqc-direct/](https://quantumcomputinginc.com/learn/reference-documentation/eqc-direct/)

This neither should redirect to another package documentation link. Please reach out if you have questions.

**Comment by RussellHuffman** [comment]
I believe this is now fixed. @rafikalid can we close this?

**Comment by RussellHuffman** [comment]
This is fixed. Thank you @rafikalid
