### ISSUE TITLE
Images not showing up in EmuCore Reference documentation seems like a pathing issue in the website

### ISSUE THREAD

**Issue by qci-github** [qci-enablement/qci-data#63]
Images aren't showing up on either of these pages:
[NARMA10](https://quantumcomputinginc.com/learn/reference-documentation/emucore-direct/v1.0.3/univariate-time-series-forecasting-narma10)
[Basic Usage](https://quantumcomputinginc.com/learn/reference-documentation/emucore-direct/v1.0.3/basic-usage)

**Comment by RussellHuffman** [comment]
This is fixed. Thank you @rafikalid
