### ISSUE TITLE
Issues with account access from dirac-3 quick start

### ISSUE THREAD

**Issue by RussellHuffman** [qci-enablement/qci-data#65]
I was running the Dirac-3 quick start tutorial and was getting this error:

`HTTPError: 401 Client Error: Unauthorized for url: https://api.qci-prod.com/auth/v1/access-tokens/ with response body: {"message":"Unauthorized"}`.

I was able to debug it with Carrie because the token was properly entered. It was some nuance with the environment variables I believe. Carrie, can you add a little bit more context? I don't think I'm able to articulate the bug very well.

**Comment by thisisaus** [comment]
I'll add a comment that indicates they should use the instructions from the quick start on cloud to set the environment variables.

**Comment by thisisaus** [comment]
I cannot find the instructions, so I added some to the Dirac-3 quick start itself.

**Comment by RussellHuffman** [comment]
Even better. 
Should this issue be closed then?

**Comment by thisisaus** [comment]
PR has been merged
